name: Build
on:
  workflow_call:
    inputs:
      version:
        description: |
          Expected to be in the format: vX.Y.Z
          Used for CFBundleVersion and CFBundleShortVersionString after removing the leading "v"
          https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion
          https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring
        required: true
        type: string
      xcode_version:
        default: "13.4"
        type: string
      scheme:
        description: |
          The SCHEME value here is the name of the default Xcode project target.
          It can also be retrieved through the following automatically, but let's
          just set it to save a job step and be explicit.

            $ xcodebuild -list -json | jq --raw-output '.project.schemes[0]'
        default: "GPG Tap Notifier"
        type: string
      dstroot_path:
        default: "/tmp/GPG Tap Notifier.dst"
        type: string
    outputs:
      dmg_artifact_name:
        value: ${{ jobs.build.outputs.dmg_artifact_name }}
      zip_artifact_name:
        value: ${{ jobs.build.outputs.zip_artifact_name }}

permissions: {}

jobs:

  build:
    name: Build macOS
    runs-on: macos-12
    defaults:
      run:
        working-directory: Sources
    outputs:
      dmg_artifact_name: ${{ steps.package-dmg.outputs.DMG_FILENAME }}
      zip_artifact_name: ${{ steps.package-zip.outputs.ZIP_FILENAME }}
    steps:
      - uses: actions/checkout@v3
      - name: Parse version
        id: parse-version
        # By convention GitHub release tags start with "v". Strip this leading
        # character to create the Xcode MARKETING_VERSION.
        run: |
          VERSION_REGEX="v([0-9]+\.[0-9]+\.[0-9]+)"
          if [[ ! "${{ inputs.version }}" =~ $VERSION_REGEX ]]; then
              exit 1
          fi
          echo "::set-output name=MARKETING_VERSION::${BASH_REMATCH[1]}"
      - name: Select Xcode
        run: |
          sudo xcode-select -switch "/Applications/Xcode_${{ inputs.xcode_version }}.app"
          /usr/bin/xcodebuild -version

      # From https://betterprogramming.pub/indie-mac-app-devops-with-github-actions-b16764a3ebe7
      - name: Read Xcode build settings
        id: build-settings
        run: |
          # DSTROOT seems to differ between "xcodebuild -showBuildSettings" and
          # "xcodebuild install". Set it to a hard-coded path so this is
          # predictable.
          XCODE_BUILD_SETTINGS=$(xcodebuild -scheme "${{ inputs.scheme }}" DSTROOT="${{ inputs.dstroot_path }}" -showBuildSettings -json)

          function set-output-from-proj {
            value=$(echo $XCODE_BUILD_SETTINGS | jq --raw-output ".[0].buildSettings.$1")
            echo "::set-output name=$1::$value"
          }

          # https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html
          set-output-from-proj FULL_PRODUCT_NAME
          set-output-from-proj INSTALL_DIR # Equivalent to $DSTROOT/INSTALL_PATH
          set-output-from-proj PRODUCT_MODULE_NAME
          set-output-from-proj PRODUCT_NAME

      - name: Run xcodebuild install
        run: |
          xcodebuild \
            -scheme "${{ inputs.scheme }}" \
            DSTROOT="${{ inputs.dstroot_path }}" \
            MARKETING_VERSION="${{ steps.parse-version.outputs.MARKETING_VERSION }}" \
            CURRENT_PROJECT_VERSION="${{ steps.parse-version.outputs.MARKETING_VERSION }}.${{ github.run_id }}" \
            install | xcpretty

      - name: Package ${{ steps.build-settings.outputs.PRODUCT_MODULE_NAME }}.dmg
        id: package-dmg
        run: |
          DMG_FILENAME="${{ steps.build-settings.outputs.PRODUCT_MODULE_NAME }}.dmg"
          echo "::set-output name=DMG_FILENAME::$DMG_FILENAME"

          # Using /private/tmp over /tmp due to https://github.com/actions/upload-artifact/issues/92
          DMG_PATH="/private/tmp/$DMG_FILENAME"
          echo "::set-output name=DMG_PATH::$DMG_PATH"

          hdiutil create \
            -fs HFS+ \
            -srcfolder "${{ steps.build-settings.outputs.INSTALL_DIR }}/${{ steps.build-settings.outputs.FULL_PRODUCT_NAME }}" \
            -volname "${{ steps.build-settings.outputs.PRODUCT_NAME }}" \
            "$DMG_PATH"

      - name: Package ${{ steps.build-settings.outputs.PRODUCT_MODULE_NAME }}.zip
        id: package-zip
        run: |
          ZIP_FILENAME="${{ steps.build-settings.outputs.PRODUCT_MODULE_NAME }}.zip"
          echo "::set-output name=ZIP_FILENAME::$ZIP_FILENAME"

          # Using /private/tmp over /tmp due to https://github.com/actions/upload-artifact/issues/92
          ZIP_PATH="/private/tmp/$ZIP_FILENAME"
          echo "::set-output name=ZIP_PATH::$ZIP_PATH"

          cd "${{ steps.build-settings.outputs.INSTALL_DIR }}"
          zip -r "$ZIP_PATH" "${{ steps.build-settings.outputs.FULL_PRODUCT_NAME }}"

      - name: Document release artifact SHAs
        run: |
          shasum --algorithm 512 "${{ steps.package-dmg.outputs.DMG_PATH }}"
          shasum --algorithm 512 "${{ steps.package-zip.outputs.ZIP_PATH }}"

      - name: Upload ${{ steps.package-dmg.outputs.DMG_FILENAME }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package-dmg.outputs.DMG_FILENAME }}
          path: "${{ steps.package-dmg.outputs.DMG_PATH }}"

      - name: Upload ${{ steps.package-zip.outputs.ZIP_FILENAME }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package-zip.outputs.ZIP_FILENAME }}
          path: "${{ steps.package-zip.outputs.ZIP_PATH }}"
