name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version: "${{ github.ref_name }}"

  # Not fully tested
  github_release:
    runs-on: ubuntu-latest
    name: Upload to GitHub Release
    needs: [build]
    steps:
      - name: Download .dmg.zip
        id: download_dmg_artifact
        uses: actions/download-artifact@v3
        with:
          name: GPG_Tap_Notifier.dmg.zip
      - name: Unzip
        run: unzip ${{ steps.download_dmg_artifact.outputs.download-path }}/GPG_Tap_Notifier.dmg.zip
      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ steps.download_dmg_artifact.outputs.download-path }}/GPG_Tap_Notifier.dmg"
